# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a parent image
FROM node:14-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application for Cloudflare Workers
RUN npm run build
RUN npm run build:worker

# Use a smaller base image for the final build
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app /app

# Expose the application on the port that Miniflare uses
EXPOSE 8787

# Command to run the application
CMD ["miniflare", "--build-command", "npm run dev:worker", "--watch"]
