name = "marbiano"
type = "javascript"
workers_dev = false
account_id = "71fabf45fe62453d4c8554e835ca4781"
zone_id = "9b0305767b86bbda17623a2608822a1b"
route = "marbiano.dev/*"
compatibility_date = "2021-11-22"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[vars]
DATOCMS_API_TOKEN = "4edd16d6371266672892b34745cc15"